apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "crusoe-registry-pruner.name" . }}
  labels:
    {{- include "crusoe-registry-pruner.labels" . | nindent 4 }}
data:
  {{- with .Values.log }}
  LOG_FORMAT: {{ .format | quote }}
  LOG_LEVEL: {{ .level | quote }}
  LOG_SOURCE: {{ .source | quote }}
  {{- end }}
  {{- with .Values.config }}
  {{- if .ageFrom }}
  AGE_FROM: {{ .ageFrom | quote }}
  {{- end }}
  {{- if .deleteImages }}
  DELETE_IMAGES: {{ .deleteImages | quote }}
  {{- end }}
  {{- if .dryRun }}
  DRY_RUN: {{ .dryRun | quote }}
  {{- end }}
  {{- if .keepTagPrefixes }}
  KEEP_TAG_PREFIXES: {{ .keepTagPrefixes | compact | join "," | quote }}
  {{- end }}
  {{- if .maxAge }}
  MAX_AGE: {{ .maxAge | quote }}
  {{- end }}
  {{- if .tagState }}
  TAG_STATE: {{ .tagState | quote }}
  {{- end }}
  {{- if .timeout }}
  TIMEOUT: {{ .timeout | quote }}
  {{- end }}
  {{- if .pruneNeverPulled }}
  PRUNE_NEVER_PULLED: {{ .pruneNeverPulled | quote }}
  {{- end }}
  {{- end }}
